# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 1000

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$kubernetes\
$sudo\
$cmd_duration\
$fill \
$time \
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""


# $battery\
# $time\
# $status\

#right_format = "$time"
[time]
disabled = false

[shlvl]
disabled = false
threshold = 3

[status]
#style = 'bg:blue'
symbol = ' 🔴 '
success_symbol = ' 🟢'
format = '[$symbol$maybe_int]($style) '
map_symbol = true
disabled = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[gcloud]
detect_env_vars = [ "CLOUDSDK" ]
#symbol = '️'
[gcloud.region_aliases]
us-central1 = 'uc1'
asia-northeast1 = 'an1'


[git_branch]
always_show_remote=true

[kubernetes]
format = 'on ⛵ [$context](bold yellow) [\($namespace\)](green)'
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\w-]+)' = 'gke-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'
